# Generated by Django 4.1.2 on 2022-10-28 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='clients.category', verbose_name='Categoria')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='clients.client', verbose_name='Cliente')),
                ('contacts', models.ManyToManyField(blank=True, related_name='newsletters', to='newsletter.contact', verbose_name='Contatos')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Domingo'), (2, 'Segunda-feira'), (3, 'Terça-feira'), (4, 'Quarta-feira'), (5, 'Quinta-feira'), (6, 'Sexta-feira'), (7, 'Sábado')], verbose_name='Dia')),
                ('time', models.TimeField(verbose_name='Horário')),
                ('newsletter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='newsletter.newsletter', verbose_name='Agenda')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'ordering': ['day', 'time'],
            },
        ),
    ]
