# Generated by Django 4.1.2 on 2023-03-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_newsletter_document_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='newsletter_layout',
            field=models.CharField(choices=[('BÁSICO', 'BÁSICO'), ('CATEGORIA COM CORES PERSONALIZADAS', 'CATEGORIA COM CORES PERSONALIZADAS'), ('PERSONALIZADO', 'PERSONALIZADO'), ('REDES SOCIAIS', 'REDES SOCIAIS')], default='CATEGORIA COM CORES PERSONALIZADAS', max_length=100, verbose_name='Layout'),
        ),
    ]
