# Generated by Django 4.1.2 on 2023-03-22 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_newsletter_newsletter_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')], verbose_name='Dia'),
        ),
        migrations.CreateModel(
            name='ScheduleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('finished', models.DateTimeField(blank=True, null=True, verbose_name='Finalizada')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsletter.schedule', verbose_name='Agenda')),
            ],
            options={
                'verbose_name': 'Histórico de Agenda Newsletter',
                'verbose_name_plural': 'Históricos de Agenda Newsletter',
                'ordering': ['-created'],
            },
        ),
    ]
