# Generated by Django 4.1.2 on 2023-03-22 23:49

from django.db import migrations


def update_weekday(apps, schema_editor):
    Schedule = apps.get_model('newsletter', 'Schedule')
    for schedule in Schedule.objects.all():
        if schedule.day == 1:
            schedule.day = 7
        else:
            schedule.day = schedule.day - 1
        schedule.save()


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_alter_schedule_day_schedulehistory'),
    ]

    operations = [
        migrations.RunPython(update_weekday)
    ]
