# Generated by Django 4.1.2 on 2023-03-26 16:03

from django.db import migrations


def create_periodic_task(apps, schema_editor):
    CrontabSchedule = apps.get_model('django_celery_beat.CrontabSchedule')
    PeriodicTask = apps.get_model('django_celery_beat.PeriodicTask')
    schedule,  _ = CrontabSchedule.objects.get_or_create(
        minute='*/30',
        hour='*',
        day_of_week='*',
        day_of_month='*',
        month_of_year='*',
    )
    PeriodicTask.objects.create(
        crontab=schedule,
        name='send_newsletter',
        task='nxt.newsletter.tasks.send_newsletter',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0006_auto_20230322_2049'),
    ]

    operations = [
        migrations.RunPython(create_periodic_task)
    ]
