# Generated by Django 4.2 on 2023-04-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0023_clipping_newsletter_sent"),
        ("newsletter", "0007_auto_20230326_1303"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsletter",
            name="category",
        ),
        migrations.AddField(
            model_name="newsletter",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="newsletters",
                to="clients.category",
                verbose_name="Categorias",
            ),
        ),
    ]
