# Generated by Django 4.1.2 on 2023-03-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('sender', models.EmailField(max_length=254, verbose_name='Remetente')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Destinatário')),
                ('subject', models.CharField(max_length=100, verbose_name='Assunto')),
                ('body', models.TextField(blank=True, verbose_name='Conteúdo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('refused', 'Rejeitado')], default='pending', max_length=20, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['-created'],
            },
        ),
    ]
