# Generated by Django 4.1.2 on 2022-12-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bank_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['code'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
    ]
