# Generated by Django 4.1.2 on 2023-01-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bank_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'ordering': ['code'], 'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
    ]
