# Generated by Django 4.1.2 on 2022-10-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_source_city_source_marketing_value_source_priority_and_more'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='companies', to='media.source', verbose_name='Veículos'),
        ),
    ]
