# Generated by Django 4.1.2 on 2022-10-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='sources',
        ),
    ]
