# Generated by Django 4.1.2 on 2022-11-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_company_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='county_registration',
            field=models.CharField(blank=True, max_length=20, verbose_name='Inscrição Municipal'),
        ),
    ]
