# Generated by Django 4.1.2 on 2023-01-02 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_county_registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('document_type', models.CharField(choices=[('Alvará de funcionamento', 'Alvará de funcionamento'), ('Balanço', 'Balanço'), ('Certidão de Falência e Concordata', 'Certidão de Falência e Concordata'), ('Certidão do CNJ', 'Certidão do CNJ'), ('Certidão Estadual', 'Certidão Estadual'), ('Certidão GDF - Juntos a Orgãos Públicos', 'Certidão GDF - Juntos a Orgãos Públicos'), ('Certidão GDF - Juntos ao GDF', 'Certidão GDF - Juntos ao GDF'), ('Certidão Municipal', 'Certidão Municipal'), ('Certidão Simplificada - Junta Comercial', 'Certidão Simplificada - Junta Comercial'), ('Certidão Trabalhista GDF', 'Certidão Trabalhista GDF'), ('CND Receita Federal / PREVI - Certidão Negativa de Débitos', 'CND Receita Federal / PREVI - Certidão Negativa de Débitos'), ('CNDT - Certidão Negativa de Débitos Trabalhistas', 'CNDT - Certidão Negativa de Débitos Trabalhistas'), ('CNPJ - Cadastro de Pessoa Jurídica', 'CNPJ - Cadastro de Pessoa Jurídica'), ('Comprovante de pagamentos dos funcionários', 'Comprovante de pagamentos dos funcionários'), ('Consulta de Opção do Simples Nacional', 'Consulta de Opção do Simples Nacional'), ('Contrato Social', 'Contrato Social'), ('Contratos com fornecedores', 'Contratos com fornecedores'), ('CRF - Certificado de Regularidade do FGTS', 'CRF - Certificado de Regularidade do FGTS'), ('Documentação dos Sócios', 'Documentação dos Sócios'), ('EPP', 'EPP'), ('Imposto de renda PJ', 'Imposto de renda PJ'), ('Inscrição Estadual', 'Inscrição Estadual'), ('Jornalista', 'Jornalista'), ('Marketing', 'Marketing'), ('Portal Transparência', 'Portal Transparência'), ('SICAF - Declaração de Situação de Cadastro', 'SICAF - Declaração de Situação de Cadastro'), ('SIMPLES - Termo de Deferimento da Opção pelo Simples Nacional', 'SIMPLES - Termo de Deferimento da Opção pelo Simples Nacional'), ('TCU', 'TCU'), ('Termo de abertura e encerramento', 'Termo de abertura e encerramento')], max_length=100, verbose_name='Tipo do Documento')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('reference_date', models.DateField(verbose_name='Data de Referência')),
                ('start_date', models.DateField(verbose_name='Válido de')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Até a data')),
                ('document_file', models.FileField(upload_to='companies/documents', verbose_name='Arquivo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created'],
            },
        ),
    ]
