# Generated by Django 4.1.2 on 2022-10-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('crawler', models.CharField(max_length=30, verbose_name='Nome do Crawler')),
                ('finish', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado')),
                ('status', models.CharField(max_length=30, verbose_name='Situação')),
                ('error_details', models.TextField(blank=True, verbose_name='Detalhes de Erro')),
                ('log', models.TextField(blank=True, verbose_name='Log')),
            ],
            options={
                'verbose_name': 'Execução',
                'verbose_name_plural': 'Execuções',
                'ordering': ['-created'],
            },
        ),
    ]
