# Generated by Django 4.1.2 on 2023-02-08 20:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationmodel',
            options={'ordering': ['-modified'], 'verbose_name': 'Modelo de Notificação', 'verbose_name_plural': 'Modelo de Notificações'},
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Conteúdo'),
        ),
    ]
