# Generated by Django 4.1.2 on 2022-10-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('publish_date', models.DateTimeField(verbose_name='Data Publicação')),
            ],
            options={
                'verbose_name': 'Mídia',
                'verbose_name_plural': 'Mídias',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador')),
                ('source_type', models.CharField(choices=[('diariooficial', 'Diário Oficial'), ('tv', 'TV'), ('radio', 'Rádio')], max_length=30, verbose_name='Tipo do Veículo')),
                ('territory_id', models.CharField(max_length=10, unique=True, verbose_name='Id do Território')),
            ],
            options={
                'verbose_name': 'Veículo de Informação',
                'verbose_name_plural': 'Veículos de Informações',
            },
        ),
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='Ordem')),
                ('document', models.FileField(blank=True, null=True, upload_to='media/document', verbose_name='Documento')),
                ('transcription', models.TextField(blank=True, verbose_name='Transcrição')),
                ('processed', models.BooleanField(blank=True, default=False, verbose_name='Processado')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='media.media', verbose_name='Conteúdo da Mídia')),
            ],
            options={
                'verbose_name': 'Conteúdo da Mídia',
                'verbose_name_plural': 'Conteúdos das Mídia',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='media',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medias', to='media.source', verbose_name='Veículo'),
        ),
    ]
