# Generated by Django 4.1.2 on 2022-10-26 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_company_sources'),
        ('media', '0002_source_city_source_marketing_value_source_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='companies.company', verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
