# Generated by Django 4.1.2 on 2022-10-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_source_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='slug',
        ),
    ]
