# Generated by Django 4.1.2 on 2022-10-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_remove_source_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['name'], 'verbose_name': 'Veículo de Informação', 'verbose_name_plural': 'Veículos de Informações'},
        ),
    ]
