# Generated by Django 4.1.2 on 2022-11-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_alter_source_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='publish_days',
            field=models.JSONField(blank=True, null=True, verbose_name='Dias de Publicação'),
        ),
        migrations.AddField(
            model_name='source',
            name='website',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço do Site'),
        ),
    ]
