# Generated by Django 4.1.2 on 2022-11-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_source_publish_days_source_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='errors',
            field=models.TextField(blank=True, verbose_name='Erros de Processamento'),
        ),
    ]
