# Generated by Django 4.1.2 on 2022-11-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_mediacontent_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Diário', 'Diário'), ('Semanal', 'Semanal'), ('Quinzenal', 'Quinzenal'), ('Mensal', 'Mensal'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=20, verbose_name='Periodicidade'),
        ),
    ]
