# Generated by Django 4.1.2 on 2022-11-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_source_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_content_type',
            field=models.CharField(blank=True, choices=[('ANÚNCIO/PUBLICIDADE', 'ANÚNCIO/PUBLICIDADE'), ('AO VIVO E CHAMADA', 'AO VIVO E CHAMADA'), ('ARTIGO', 'ARTIGO'), ('CARTA/EMAIL', 'CARTA/EMAIL'), ('CHAMADA DE CAPA', 'CHAMADA DE CAPA'), ('CHARGE', 'CHARGE'), ('CINEMA', 'CINEMA'), ('COLUNA', 'COLUNA'), ('CRÔNICA', 'CRÔNICA'), ('CURTAS', 'CURTAS'), ('DEBATE', 'DEBATE'), ('EDITAL', 'EDITAL'), ('EDITORIAL', 'EDITORIAL'), ('ENTREVISTA', 'ENTREVISTA'), ('ESCALADA', 'ESCALADA'), ('FEED', 'FEED'), ('IGTV', 'IGTV'), ('INSERÇÃO ELEITORAL', 'INSERÇÃO ELEITORAL'), ('MATÉRIA', 'MATÉRIA'), ('MATÉRIA COM CHAMADA', 'MATÉRIA COM CHAMADA'), ('NOTA', 'NOTA'), ('PROGRAMA ELEITORAL', 'PROGRAMA ELEITORAL'), ('REPORTAGEM', 'REPORTAGEM'), ('STORIES', 'STORIES')], max_length=50, verbose_name='Tipo da Notícia'),
        ),
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.URLField(blank=True, verbose_name='Link do Conteúdo'),
        ),
    ]
