# Generated by Django 4.1.2 on 2022-11-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_media_media_content_type_media_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='authors',
            field=models.CharField(blank=True, help_text='Use vírgula para separar os autores', max_length=255, verbose_name='Autores'),
        ),
        migrations.AddField(
            model_name='media',
            name='resume',
            field=models.CharField(blank=True, max_length=255, verbose_name='Resumo'),
        ),
    ]
