# Generated by Django 4.1.2 on 2022-11-17 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_media_authors_media_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.URLField(blank=True, verbose_name='Imagem'),
        ),
    ]
