# Generated by Django 4.1.2 on 2022-11-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_media_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.CharField(blank=True, max_length=255, verbose_name='Imagem'),
        ),
    ]
