# Generated by Django 4.1.2 on 2022-11-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_alter_media_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link do Conteúdo'),
        ),
    ]
