# Generated by Django 4.1.2 on 2022-12-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0014_alter_media_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='processed_clipping',
            field=models.BooleanField(default=False, verbose_name='Processado Recorte'),
        ),
    ]
