# Generated by Django 4.1.2 on 2022-12-12 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0015_mediacontent_processed_clipping'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Editorial')),
                ('date_xpath', models.CharField(max_length=100, verbose_name='Caminho para a Data')),
                ('date_format', models.CharField(max_length=50, verbose_name='Formato da data')),
                ('title_xpath', models.CharField(max_length=100, verbose_name='Caminho para o Título')),
                ('author_xpath', models.CharField(max_length=100, verbose_name='Caminho para o Autor')),
                ('text_xpath', models.CharField(max_length=100, verbose_name='Caminho para o Texto')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editorials', to='media.source', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriais',
                'ordering': ['name'],
            },
        ),
    ]
