# Generated by Django 4.1.2 on 2022-12-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0016_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='url',
            field=models.CharField(default='', max_length=255, verbose_name='Link do Editorial'),
        ),
    ]
