# Generated by Django 4.1.2 on 2022-12-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0017_editorial_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='url_xpath',
            field=models.CharField(default='', max_length=100, verbose_name='Caminho para o Link'),
        ),
    ]
