# Generated by Django 4.1.2 on 2022-12-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0018_editorial_url_xpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='date_format',
            field=models.CharField(choices=[('d/m/Y', 'DD/MM/AAAA'), ('d/m/y', 'DD/MM/AA'), ('d/m/Y \\à\\s H:m', 'DD/MM/AAAA às H:m'), ('d/m/Y H:m', 'DD/MM/AAAA H:m')], max_length=50, verbose_name='Formato da data'),
        ),
    ]
