# Generated by Django 4.1.2 on 2022-12-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0020_alter_editorial_options_editorial_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='frequency',
            field=models.CharField(blank=True, choices=[('Diário', 'Diário'), ('Semanal', 'Semanal'), ('Quinzenal', 'Quinzenal'), ('Mensal', 'Mensal'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=20, verbose_name='Periodicidade'),
        ),
    ]
