# Generated by Django 4.1.2 on 2023-01-11 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0021_alter_editorial_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='publish_date_raw',
            field=models.CharField(blank=True, max_length=50, verbose_name='Data Publicação (texto)'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='date_format',
            field=models.CharField(choices=[('d/m/Y', 'DD/MM/AAAA'), ('d/m/y', 'DD/MM/AA'), ('l, d \\d\\e F \\d\\e Y, H:i', 'D. Semana, D de M de A, H:m'), ('l, d \\d\\e F \\d\\e Y', 'D. Semana, D de M de A'), ('d/m/Y \\à\\s H:i', 'DD/MM/AAAA às H:m'), ('d/m/Y H:i', 'DD/MM/AAAA H:m')], max_length=50, verbose_name='Formato da data'),
        ),
    ]
