# Generated by Django 4.1.2 on 2023-01-11 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0022_media_publish_date_raw_alter_editorial_date_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='editorial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.editorial', verbose_name='editorial'),
        ),
    ]
