# Generated by Django 4.1.2 on 2023-01-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0023_media_editorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='publish_date_raw',
            field=models.CharField(blank=True, max_length=255, verbose_name='Data Publicação (texto)'),
        ),
    ]
