# Generated by Django 4.1.2 on 2023-01-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0024_alter_media_publish_date_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='author_xpath',
            field=models.CharField(blank=True, max_length=100, verbose_name='Caminho para o Autor'),
        ),
        migrations.AddField(
            model_name='source',
            name='date_format',
            field=models.CharField(blank=True, choices=[('d/m/Y', 'DD/MM/AAAA'), ('d/m/y', 'DD/MM/AA'), ('l, d \\d\\e F \\d\\e Y, H:i', 'D. Semana, D de M de A, H:m'), ('l, d \\d\\e F \\d\\e Y', 'D. Semana, D de M de A'), ('d/m/Y \\à\\s H:i', 'DD/MM/AAAA às H:m'), ('d/m/Y H:i', 'DD/MM/AAAA H:m')], max_length=50, verbose_name='Formato da data'),
        ),
        migrations.AddField(
            model_name='source',
            name='date_xpath',
            field=models.CharField(blank=True, max_length=100, verbose_name='Caminho para a Data'),
        ),
        migrations.AddField(
            model_name='source',
            name='text_xpath',
            field=models.CharField(blank=True, max_length=100, verbose_name='Caminho para o Texto'),
        ),
        migrations.AddField(
            model_name='source',
            name='title_xpath',
            field=models.CharField(blank=True, max_length=100, verbose_name='Caminho para o Título'),
        ),
        migrations.AddField(
            model_name='source',
            name='url_xpath',
            field=models.CharField(blank=True, max_length=100, verbose_name='Caminho para o Link'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='author_xpath',
            field=models.CharField(blank=True, max_length=100, verbose_name='Caminho para o Autor'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='date_format',
            field=models.CharField(blank=True, choices=[('d/m/Y', 'DD/MM/AAAA'), ('d/m/y', 'DD/MM/AA'), ('l, d \\d\\e F \\d\\e Y, H:i', 'D. Semana, D de M de A, H:m'), ('l, d \\d\\e F \\d\\e Y', 'D. Semana, D de M de A'), ('d/m/Y \\à\\s H:i', 'DD/MM/AAAA às H:m'), ('d/m/Y H:i', 'DD/MM/AAAA H:m')], max_length=50, verbose_name='Formato da data'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='date_xpath',
            field=models.CharField(blank=True, max_length=100, verbose_name='Caminho para a Data'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='text_xpath',
            field=models.CharField(blank=True, max_length=100, verbose_name='Caminho para o Texto'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='title_xpath',
            field=models.CharField(blank=True, max_length=100, verbose_name='Caminho para o Título'),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='url_xpath',
            field=models.CharField(blank=True, max_length=100, verbose_name='Caminho para o Link'),
        ),
    ]
