# Generated by Django 4.1.2 on 2023-01-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0026_source_url_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='use_configuration_source',
            field=models.BooleanField(default=True, verbose_name='Usar Configuração do Veículo'),
        ),
    ]
