# Generated by Django 4.1.2 on 2023-01-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0027_editorial_use_configuration_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='city',
        ),
    ]
