# Generated by Django 4.1.2 on 2023-01-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_city'),
        ('media', '0028_remove_source_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.city'),
        ),
    ]
