# Generated by Django 4.1.2 on 2023-03-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0031_alter_source_city_alter_source_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='media.source', verbose_name='Veículo'),
        ),
    ]
