# Generated by Django 4.1.2 on 2023-03-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0032_alter_media_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='headline_xpath',
            field=models.CharField(blank=True, max_length=100, verbose_name='Caminho para o Resumo/Subtítulo'),
        ),
        migrations.AddField(
            model_name='source',
            name='headline_xpath',
            field=models.CharField(blank=True, max_length=100, verbose_name='Caminho para o Resumo/Subtítulo'),
        ),
    ]
