# Generated by Django 4.1.2 on 2023-03-16 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0033_editorial_headline_xpath_source_headline_xpath'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('pdf_file', models.FileField(upload_to='media/newspaper', verbose_name='Arquivo PDF')),
                ('publish_date', models.DateField(verbose_name='Data Publicação')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspapers', to='media.source', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Impresso',
                'verbose_name_plural': 'Impressos',
                'ordering': ['-publish_date'],
            },
        ),
    ]
