# Generated by Django 4.1.2 on 2023-03-16 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_document'),
        ('media', '0034_newspaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='newspapers', to='companies.company', verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
