# Generated by Django 4.1.2 on 2023-03-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0036_mediacontent_newspaper_mediacontent_newspaper_crop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Link da Editoria'),
        ),
    ]
