# Generated by Django 4.1.2 on 2023-03-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0037_alter_editorial_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='audience',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantiade de público'),
        ),
    ]
