# Generated by Django 4.1.2 on 2023-03-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0038_source_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='marketing_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Vl publicit. padrão'),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('diariooficial', 'Diário Oficial'), ('tv', 'TV'), ('radio', 'Rádio'), ('site', 'Site'), ('blog', 'Blog'), ('impresso', 'Impresso'), ('revista', 'Revista')], max_length=30, verbose_name='Tipo do Veículo'),
        ),
    ]
