# Generated by Django 4.1.2 on 2022-10-26 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import nxt.security.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NXTPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('code', models.SlugField(unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Permissão NXT',
                'verbose_name_plural': 'Permissões NXT',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('expiration', models.DateField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('profile', models.CharField(choices=[('administrador', 'Administrador'), ('funcionario', 'Funcionário'), ('cliente', 'Cliente')], default='cliente', max_length=20, verbose_name='Perfil')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telefone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos', verbose_name='Foto')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Equipe')),
                ('last_access', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Último acesso')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='clients.client', verbose_name='Cliente')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('nxt_permissions', models.ManyToManyField(blank=True, to='security.nxtpermission')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['name'],
            },
            managers=[
                ('objects', nxt.security.models.UserManager()),
            ],
        ),
    ]
