# Generated by Django 4.1.2 on 2022-10-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_company_sources'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nxtpermission',
            options={'ordering': ['id'], 'verbose_name': 'Permissão NXT', 'verbose_name_plural': 'Permissões NXT'},
        ),
        migrations.AddField(
            model_name='user',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='total_users', to='companies.company', verbose_name='Todas as Empresas'),
        ),
    ]
