# Generated by Django 4.1.2 on 2022-12-21 10:01

from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bank'),
        ('security', '0002_alter_nxtpermission_options_user_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_bank', to='core.bank', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_agency',
            field=models.CharField(blank=True, max_length=10, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_operation',
            field=models.CharField(blank=True, max_length=50, verbose_name='Operação'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_pix1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_bank_pix1', to='core.bank', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_pix1_key_type',
            field=models.CharField(blank=True, choices=[('Celular', 'Celular'), ('CPF', 'CPF'), ('E-mail', 'E-mail'), ('Aleatória', 'Aleatória')], max_length=20, verbose_name='Tipo da Chave'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_pix1_value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_pix2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_bank_pix2', to='core.bank', verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_pix2_key_type',
            field=models.CharField(blank=True, choices=[], max_length=20, verbose_name='Tipo da Chave'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_pix2_value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='user',
            name='childrens_cpfs',
            field=models.CharField(blank=True, max_length=100, verbose_name='CPF filho(s)'),
        ),
        migrations.AddField(
            model_name='user',
            name='childrens_names',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nome dos Filhos'),
        ),
        migrations.AddField(
            model_name='user',
            name='complement',
            field=models.CharField(blank=True, max_length=50, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='user',
            name='cpf',
            field=localflavor.br.models.BRCPFField(blank=True, max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_card',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número da Carteira de Motorista'),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_card_entity_uf',
            field=models.CharField(blank=True, max_length=50, verbose_name='Órgão Expedidor/UF'),
        ),
        migrations.AddField(
            model_name='user',
            name='driver_card_expedition',
            field=models.DateField(blank=True, null=True, verbose_name='Data da emissão'),
        ),
        migrations.AddField(
            model_name='user',
            name='equipament_brand',
            field=models.CharField(blank=True, max_length=50, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='user',
            name='equipament_dvr_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca/modelo/descrição'),
        ),
        migrations.AddField(
            model_name='user',
            name='equipament_dvr_local',
            field=models.CharField(blank=True, max_length=50, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='user',
            name='equipament_dvr_local_recorded',
            field=models.TextField(blank=True, verbose_name='Canais gravados'),
        ),
        migrations.AddField(
            model_name='user',
            name='equipament_dvr_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de DVRs'),
        ),
        migrations.AddField(
            model_name='user',
            name='equipament_dvr_status',
            field=models.CharField(blank=True, help_text='em uso/parado/queimado/estragado', max_length=50, verbose_name='Situação'),
        ),
        migrations.AddField(
            model_name='user',
            name='equipament_dvr_total_channels',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número total de canais'),
        ),
        migrations.AddField(
            model_name='user',
            name='equipament_has_dvr',
            field=models.BooleanField(default=False, verbose_name='Possui DVR'),
        ),
        migrations.AddField(
            model_name='user',
            name='equipament_hd',
            field=models.CharField(blank=True, max_length=50, verbose_name='HD'),
        ),
        migrations.AddField(
            model_name='user',
            name='equipament_hd_used',
            field=models.CharField(blank=True, max_length=50, verbose_name='Espaço em Uso'),
        ),
        migrations.AddField(
            model_name='user',
            name='equipament_memory',
            field=models.CharField(blank=True, max_length=50, verbose_name='Memória'),
        ),
        migrations.AddField(
            model_name='user',
            name='equipament_model',
            field=models.CharField(blank=True, max_length=50, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='user',
            name='equipament_processor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Processador'),
        ),
        migrations.AddField(
            model_name='user',
            name='equipament_type',
            field=models.CharField(blank=True, help_text='PC/Notebook', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='user',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome do Pai'),
        ),
        migrations.AddField(
            model_name='user',
            name='has_equipament',
            field=models.BooleanField(default=False, verbose_name='Possui Equipamento'),
        ),
        migrations.AddField(
            model_name='user',
            name='home_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefone Residencial'),
        ),
        migrations.AddField(
            model_name='user',
            name='internet_contracted_speed',
            field=models.CharField(blank=True, max_length=50, verbose_name='Velocidade Contratada'),
        ),
        migrations.AddField(
            model_name='user',
            name='internet_cost',
            field=models.CharField(blank=True, max_length=50, verbose_name='Valor de ajuda de custo'),
        ),
        migrations.AddField(
            model_name='user',
            name='internet_download_speed',
            field=models.CharField(blank=True, max_length=50, verbose_name='Velocidade Download'),
        ),
        migrations.AddField(
            model_name='user',
            name='internet_others_providers',
            field=models.CharField(blank=True, max_length=100, verbose_name='Outra opções de provedor'),
        ),
        migrations.AddField(
            model_name='user',
            name='internet_provider',
            field=models.CharField(blank=True, max_length=50, verbose_name='Provedor'),
        ),
        migrations.AddField(
            model_name='user',
            name='internet_type',
            field=models.CharField(blank=True, help_text='Banda Larga/fibra', max_length=30, verbose_name='Tipo de Internet'),
        ),
        migrations.AddField(
            model_name='user',
            name='internet_upload_speed',
            field=models.CharField(blank=True, max_length=50, verbose_name='Velocidade Upload'),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a)', 'Casado(a)'), ('Separado(a) judicialmente', 'Separado(a) judicialmente'), ('Divorciado(a)', 'Divorciado(a)'), ('Viúvo(a)', 'Viúvo(a)'), ('União Estável', 'União Estável'), ('Outro', 'Outro')], max_length=30, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='user',
            name='mothers_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='user',
            name='naturalness',
            field=models.CharField(blank=True, max_length=50, verbose_name='Naturalidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='user',
            name='number_of_children',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Números de filhos'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_contact',
            field=models.TextField(blank=True, verbose_name='Informe telefone de parentes ou outros meios que possam ser utilizados para contato com o (a) colaborador (a), colocar telefone, nome e grau de parentesco:'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_message',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefone Recardo'),
        ),
        migrations.AddField(
            model_name='user',
            name='pis_pasep',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pis/Pasep'),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='user',
            name='rg',
            field=models.CharField(blank=True, max_length=10, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='user',
            name='rg_entity_uf',
            field=models.CharField(blank=True, max_length=50, verbose_name='Órgão Expedidor/UF'),
        ),
        migrations.AddField(
            model_name='user',
            name='rg_expedition',
            field=models.DateField(blank=True, null=True, verbose_name='Data de emissão'),
        ),
        migrations.AddField(
            model_name='user',
            name='voter_registration',
            field=models.CharField(blank=True, max_length=20, verbose_name='Título de Eleitor'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, verbose_name='Whatsapp'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_card',
            field=models.CharField(blank=True, max_length=20, verbose_name='Carteira de Trabalho'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefone Celular'),
        ),
    ]
