# Generated by Django 4.1.2 on 2023-01-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_user_naturalness_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degress',
            field=models.CharField(blank=True, choices=[('Analfabeto', 'Analfabeto'), ('Fundamental incompleto', 'Fundamental incompleto'), ('Fundamental completo', 'Fundamental completo'), ('Médio incompleto', 'Médio incompleto'), ('Médio completo', 'Médio completo'), ('Superior incompleto', 'Superior incompleto'), ('Superior completo', 'Superior completo'), ('Especialização incompleta', 'Especialização incompleta'), ('Especialização completa', 'Especialização completa'), ('Mestrado incompleto', 'Mestrado incompleto'), ('Mestrado completo', 'Mestrado completo'), ('Doutorado incompleto', 'Doutorado incompleto'), ('Doutorado completo', 'Doutorado completo')], max_length=30, verbose_name='Escolaridade'),
        ),
    ]
