# Generated by Django 4.1.2 on 2023-01-02 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_user_degress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='degress',
            new_name='degree',
        ),
    ]
