# Generated by Django 4.1.2 on 2023-01-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0006_rename_degress_user_degree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bank_pix2_key_type',
            field=models.CharField(blank=True, choices=[('Celular', 'Celular'), ('CPF', 'CPF'), ('E-mail', 'E-mail'), ('Aleatória', 'Aleatória')], max_length=20, verbose_name='Tipo da Chave'),
        ),
    ]
