# Generated by Django 4.1.2 on 2023-01-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0008_user_city_user_neighborhood_user_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
