# Generated by Django 4.1.2 on 2023-01-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0011_alter_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='naturalness',
        ),
    ]
