# Generated by Django 4.1.2 on 2023-01-22 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_city'),
        ('security', '0012_remove_user_naturalness'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='naturalness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='naturalness_users', to='core.city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.city', verbose_name='Cidade'),
        ),
    ]
