# Generated by Django 4.1.2 on 2022-10-26 12:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('profile', models.CharField(choices=[('Pessoa Jurídica', 'Pessoa Jurídica'), ('Pessoa Física', 'Pessoa Física')], max_length=20, verbose_name='Perfil')),
                ('company_name', models.CharField(max_length=100, verbose_name='Razão Social / Nome')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=18, verbose_name='CNPJ/CPF')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('cell', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('brand', models.ImageField(blank=True, null=True, upload_to='clients/brand', verbose_name='Logo')),
                ('postal_code', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='Logradouro')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=50, verbose_name='Complemento')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('observations', ckeditor.fields.RichTextField(blank=True, help_text='Outras inforamções sobre o Cliente', verbose_name='Dossiê')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='companies.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('word', models.CharField(max_length=50, verbose_name='Palavra')),
                ('source', models.CharField(default='Todos', max_length=20, verbose_name='Filtro')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='clients.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Termo',
                'verbose_name_plural': 'Termos',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='NegativeWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('word', models.CharField(max_length=50, verbose_name='Palavra')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negatives', to='clients.keyword', verbose_name='Termo')),
            ],
            options={
                'verbose_name': 'Termo Negativo',
                'verbose_name_plural': 'Termos Negativos',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Clipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('keyword_used', models.CharField(max_length=50, verbose_name='Termo')),
                ('text', models.TextField(blank=True, verbose_name='Texto encontrado')),
                ('negative_words_used', models.CharField(blank=True, max_length=255, verbose_name='Termo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clippings', to='clients.client', verbose_name='Cliente')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clippings', to='media.mediacontent', verbose_name='Fonte')),
            ],
            options={
                'verbose_name': 'Recorte',
                'verbose_name_plural': 'Recortes',
                'ordering': ['-created'],
            },
        ),
    ]
