# Generated by Django 4.1.2 on 2022-10-26 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='client',
            name='sources_contract',
            field=models.ManyToManyField(blank=True, related_name='clients_contract', to='media.source', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='client',
            name='sources_main',
            field=models.ManyToManyField(blank=True, related_name='clients_main', to='media.source', verbose_name='Contrato'),
        ),
        migrations.AddField(
            model_name='category',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='clients.client', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='clients.category', verbose_name='Categoria'),
        ),
    ]
