# Generated by Django 4.1.2 on 2022-12-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.CharField(blank=True, max_length=100, verbose_name='Link Página do Cliente'),
        ),
    ]
