# Generated by Django 4.1.2 on 2022-12-07 09:47

from django.db import migrations
from django.utils.text import slugify


def update_client_slug(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')
    for client in Client.objects.all():
        client.slug = slugify(client.company_name)
        client.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_slug'),
    ]

    operations = [
        migrations.RunPython(update_client_slug)
    ]
