# Generated by Django 4.1.2 on 2022-12-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20221207_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='Link Página do Cliente'),
        ),
    ]
