# Generated by Django 4.1.2 on 2022-12-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.CharField(max_length=100, unique=True, verbose_name='Link Página do Cliente'),
        ),
    ]
