# Generated by Django 4.1.2 on 2023-01-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_client_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipping',
            name='category_used',
            field=models.CharField(default='', max_length=100, verbose_name='Categoria'),
        ),
    ]
