# Generated by Django 4.1.2 on 2023-01-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_clipping_category_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipping',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.keyword', verbose_name='Termo'),
        ),
    ]
