# Generated by Django 4.1.2 on 2023-01-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_clipping_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipping',
            name='approved',
            field=models.BooleanField(blank=True, default=True, verbose_name='Aprovado'),
        ),
        migrations.AddField(
            model_name='clipping',
            name='has_opportunity',
            field=models.BooleanField(default=False, verbose_name='Oportunidade'),
        ),
        migrations.AddField(
            model_name='clipping',
            name='has_strength',
            field=models.BooleanField(default=False, verbose_name='Força'),
        ),
        migrations.AddField(
            model_name='clipping',
            name='has_weakness',
            field=models.BooleanField(default=False, verbose_name='Fraqueza'),
        ),
        migrations.AddField(
            model_name='clipping',
            name='metion',
            field=models.CharField(blank=True, choices=[('Direta', 'Direta'), ('Indireta', 'Indireta')], max_length=20, verbose_name='Menção'),
        ),
        migrations.AddField(
            model_name='clipping',
            name='rating',
            field=models.CharField(blank=True, choices=[('Positiva', 'Positiva'), ('Negativa', 'Negativa'), ('Neutra', 'Neutra')], max_length=20, verbose_name='Classificação'),
        ),
        migrations.AddField(
            model_name='clipping',
            name='subject',
            field=models.CharField(blank=True, max_length=100, verbose_name='Assunto'),
        ),
    ]
