# Generated by Django 4.1.2 on 2023-01-16 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_clipping_approved_clipping_has_opportunity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipping',
            name='featured',
            field=models.BooleanField(blank=True, default=False, verbose_name='Destaque'),
        ),
    ]
