# Generated by Django 4.1.2 on 2023-01-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_clipping_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipping',
            name='marketign_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valoração R$'),
        ),
    ]
