# Generated by Django 4.1.2 on 2023-01-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_clipping_marketign_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clipping',
            old_name='marketign_value',
            new_name='marketing_value',
        ),
    ]
