# Generated by Django 4.1.2 on 2023-01-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_rename_marketign_value_clipping_marketing_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clipping',
            old_name='metion',
            new_name='mention',
        ),
    ]
