# Generated by Django 4.1.2 on 2023-01-18 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_rename_metion_clipping_mention'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'verbose_name': 'Termo', 'verbose_name_plural': 'Termos'},
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='word',
        ),
        migrations.AlterField(
            model_name='negativeword',
            name='word',
            field=models.CharField(max_length=100, verbose_name='Palavra'),
        ),
        migrations.CreateModel(
            name='PositiveWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='Ativo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado')),
                ('word', models.CharField(max_length=100, verbose_name='Palavra')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positives', to='clients.keyword', verbose_name='Termo')),
            ],
            options={
                'verbose_name': 'Termo Positivo',
                'verbose_name_plural': 'Termos Positivos',
                'ordering': ['word'],
            },
        ),
    ]
