# Generated by Django 4.1.2 on 2023-01-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_alter_keyword_options_remove_keyword_word_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
    ]
