# Generated by Django 4.1.2 on 2023-02-08 20:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_remove_clipping_category_used_clipping_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipping',
            name='content',
            field=models.TextField(blank=True, verbose_name='Conteúdo'),
        ),
        migrations.AddField(
            model_name='clipping',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data publicação'),
            preserve_default=False,
        ),
    ]
