# Generated by Django 4.1.2 on 2023-02-08 20:16

from django.db import migrations


def update_clipping_content(apps, schema_apps):
    Clipping = apps.get_model('clients', 'Clipping')
    for clipping in Clipping.objects.all():
        clipping.content = clipping.source.transcription
        clipping.publish_date = clipping.source.media.publish_date
        clipping.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_clipping_content_clipping_publish_date'),
    ]

    operations = [
        migrations.RunPython(update_clipping_content)
    ]
