# Generated by Django 4.1.2 on 2023-03-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0032_alter_media_source'),
        ('clients', '0021_alter_clipping_options_clipping_has_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clipping',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clippings', to='media.mediacontent', verbose_name='Fonte'),
        ),
    ]
