# Generated by Django 4.1.2 on 2023-03-22 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_alter_clipping_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipping',
            name='newsletter_sent',
            field=models.BooleanField(blank=True, default=False, verbose_name='Enviado na newsletter'),
        ),
    ]
